'use strict';
// Built-in looks. A look is only a starting point: every layer and effect stays editable.
// Positions are frame coordinates (-1..1); `v` holds the layout used for vertical (9:16) videos.
(function (VG) {
  const B = VG.analysis.binding;

  // Liquid Aurora — Aurora Chill's flowing light mixed with Liquid Neon's glowing liquid, with
  // the glow pulsing on the bass. Each variant adds its own endless zoom, and a shape-mask
  // composition sits on top.
  const LA = 'Liquid Aurora · your project';
  const FLIGHTS = '3D flights';
  const LA_PALETTE = ['#7b5cff', '#ff4fd8', '#36e2d4', '#8fb8ff', '#07051a'];
  const laGradient = () => ({ type: 'blobs', name: 'Aurora gradient', mode: 'mesh', blend: 'normal', count: 5, size: 0.7, intensity: 0.34, speed: 0.35, spread: 0.9, react: B('loud', { release: 0.6 }), glowReact: 0.35, sizeReact: 0.15, speedReact: 0.5 });
  const laLights = () => ({ type: 'blobs', name: 'Glow lights', mode: 'glow', count: 3, size: 0.4, intensity: 0.1, speed: 0.5, spread: 0.7, react: B('bass', { release: 0.3 }), glowReact: 1.1, sizeReact: 0.2 });
  const laBalls = () => ({ type: 'metaballs', name: 'Liquid balls', count: 8, size: 0.07, area: 0.6, speed: 1, style: 'fill', edge: 0.012, glow: 0.3, wobble: 0.35, react: B('bass', { release: 0.15, punch: 1.5 }), sizeReact: 0.7, glowReact: 0.6, speedReact: 1.5 });
  const laDust = () => ({ type: 'particles', name: 'Dust', mode: 'drift', count: 70, size: 0.003, speed: 0.4, twinkle: 0.7, brightness: 0.55, colorMode: 'palette', react: B('bass', { release: 0.2 }), glowReact: 0.8 });
  const laFx = () => ({
    bloom: { intensity: 0.28, threshold: 0.7, radius: 1.1, react: B('bass', { release: 0.25, punch: 1.6 }), reactAmount: 0.6 },
    chroma: { react: B('kick', { release: 0.12, threshold: 0.5 }), reactAmount: 0.003 },
    vignette: { amount: 0.4 },
    grain: { amount: 0.05, size: 1.6 },
  });

  const LIST = [
    {
      id: 'la-echo',
      group: LA,
      name: 'Echo Dive',
      blurb: 'An endless dive: everything pours out of the center in fading echoes. Concentric hexagon windows on top.',
      palette: LA_PALETTE,
      layers: [
        laGradient(), laLights(), laBalls(),
        { type: 'particles', name: 'Burst from the center', mode: 'burst', count: 180, size: 0.0028, sizeVar: 0.6, speed: 0.9, spread: 0.04, streak: 0.25, twinkle: 0.3, brightness: 0.8, colorMode: 'palette', react: B('bass', { release: 0.2 }), speedReact: 5, glowReact: 0.6, streakReact: 1 },
        { type: 'zoom', name: 'Echo tunnel', mode: 'echo', speed: 0.55, speedReact: 1.8, react: B('bass', { release: 0.3 }), trail: 0.6, echoMix: 'max', echoGain: 0.88, hueDrift: 20, spin: 6 },
        { type: 'masks', name: 'Shape masks', composition: 'concentric', shape: 'hexagon', style: 'outline', count: 4, size: 0.42, outline: 0.03, spin: 5, stroke: 0.0025, glow: 0.3, pulse: 0.06, beatMode: 'calm', tZoom: false },
      ],
      fx: laFx(),
    },
    {
      id: 'la-nested',
      group: LA,
      name: 'Nested Worlds',
      blurb: 'The picture holds a smaller copy of itself in a hexagon, forever, while the camera dives in and the whole picture slowly turns. Broken-mirror bands on top, and now and then a big shape drifts through.',
      palette: LA_PALETTE,
      layers: [
        laGradient(), laLights(), laBalls(), laDust(),
        { type: 'zoom', name: 'Nested worlds', mode: 'nested', speed: 0.25, speedReact: 0.9, react: B('bass', { release: 0.3 }), window: 'hexagon', copies: 6, ratio: 0.5, twist: 14, copyHue: 0, edge: 0.003, edgeColor: 'p4', edgeGlow: 0.35 },
        { type: 'masks', name: 'Mirror bands', composition: 'shards', count: 4, size: 0.32, spread: 0.85, rotation: 28, spin: 0, tZoom: false, stroke: 0.002, glow: 0.25, beatMode: 'snap', snapAngle: 20, snapEase: 0.9, beat: B('kick', { release: 0.15, threshold: 0.6 }) },
        { type: 'masks', name: 'Drifting masks', composition: 'drifters', shape: 'mixed', sCircle: false, style: 'mixed', count: 6, size: 1.1, minSize: 0.45, every: 10, lifeMin: 20, lifeMax: 30, fadeIn: 3, direction: 'outward',
          outline: 0.07, spread: 1, spin: 4, animate: 0.6, tTint: false, tHue: false, tInvert: false, colorChance: 0, stroke: 0, glow: 0, beatMode: 'calm', pulse: 0.05 },
      ],
      fx: Object.assign(laFx(), { camera: { spin: 180 } }),
    },
    {
      id: 'la-vortex',
      group: LA,
      name: 'Vortex',
      blurb: 'A spiral of glowing hexagons pours endlessly out of the center. Scattered shape windows reshuffle on the kicks.',
      palette: LA_PALETTE,
      layers: [
        laGradient(), laLights(),
        { type: 'vortex', name: 'Vortex', pattern: 'hex', density: 14, size: 0.7, outline: 0.1, twist: 0.35, speed: 0.35, speedReact: 1.2, rotSpeed: 5, glow: 0.25, brightness: 0.75, colorMode: 'depth', opacity: 0.6, pulse: 0.3, flash: 0.5, hole: 0.06 },
        laBalls(), laDust(),
        { type: 'masks', name: 'Shape masks', composition: 'constellation', shape: 'mixed', style: 'mixed', count: 7, size: 0.17, spread: 0.85, drift: 1, spin: 8, beatMode: 'shuffle', stroke: 0.002, glow: 0.3, pulse: 0.1 },
      ],
      fx: laFx(),
    },
    {
      id: 'la-kaleido',
      group: LA,
      name: 'Kaleidoscope',
      blurb: 'The liquid aurora through a three-mirror kaleidoscope, flowing outward in echoes. Big shapes pop up at random, showing mirrored, rotated, scaled pieces of the video.',
      palette: LA_PALETTE,
      layers: [
        laGradient(), laLights(), Object.assign(laBalls(), { style: 'neon', edge: 0.006, glow: 0.4 }), laDust(),
        { type: 'kaleido', name: 'Kaleidoscope', mode: 'triangle', size: 0.3, spin: 3, spinReact: 25, zoom: 0.85, zoomPulse: 0.1, srcX: 0.12, srcY: 0.08, drift: 0.5, seam: 0.001, seamColor: 'p4', seamGlow: 0.12 },
        { type: 'zoom', name: 'Echo tunnel', mode: 'echo', speed: 0.3, speedReact: 1.2, react: B('bass', { release: 0.3 }), trail: 0.25, echoMix: 'max', echoGain: 0.8, hueDrift: 15 },
        { type: 'masks', name: 'Shape masks', composition: 'popups', shape: 'mixed', style: 'mixed', count: 7, size: 0.8, minSize: 0.2, life: 3.2, outline: 0.07, spread: 1, spin: 14, animate: 0.6,
          tTint: false, tHue: false, tInvert: false, colorChance: 0, stroke: 0, glow: 0, beatMode: 'calm', pulse: 0.05 },
      ],
      fx: laFx(),
    },
    {
      id: 'la-flight',
      group: LA,
      name: 'Aurora Flight',
      blurb: 'Neon grid hills under your aurora sky: the land fades into the flowing light, with glass shapes drifting past.',
      palette: LA_PALETTE,
      layers: [
        laGradient(), laLights(),
        {
          type: 'flight', name: '3D flight', scene: 'terrain', terrain: 'grid', mountains: 3, size: 1.2, valley: 0.7, road: 3, height: 2.4, pitch: -6, speed: 5, winding: 1, turns: 0.8, sway: 0.4,
          grid: 2, lineW: 0.05, lineBright: 1.4, lineGlow: 0.4, lineColor: 'p3', lineColor2: 'p2', surface: 0.35, surfaceColor: 'p5',
          sky: 'transparent', sun: false, stars: 0.3, far: 60,
          figures: 'floating', figStyle: 'glass', figSpace: 16, figDensity: 0.6, figSize: 1.1, figSpread: 7, figSpin: 20, figThick: 0.03, figBright: 1.2, figGlow: 0.5,
          particles: 'dust', pCount: 500, pSize: 0.03, pStreak: 0.3,
          react: B('bass', { release: 0.3 }), speedReact: 5, glowReact: 1.1, breathe: 0.15, figPulse: 0.25, waves: 0.8, waveSpeed: 35, beatFlash: 0.6, fovPunch: 0.04,
        },
      ],
      fx: laFx(),
    },
    {
      id: 'outrun-flight',
      group: FLIGHTS,
      name: 'Outrun Flight',
      blurb: 'Race down a neon road between wireframe mountains toward a striped retro sun, flying through glowing gates.',
      palette: ['#ff2bd6', '#22e1ff', '#ffb000', '#ffffff', '#0b0418'],
      layers: [
        {
          type: 'flight', name: '3D flight', scene: 'terrain', terrain: 'valley', mountains: 7, size: 1.4, rough: 0.55, road: 4, height: 1.5, pitch: -3, fov: 72, speed: 10, winding: 0.6, turns: 0.8, bank: 0.8, sway: 0.25,
          grid: 2.5, lineW: 0.06, lineBright: 1.8, lineGlow: 0.35, surface: 0.15,
          sky: 'gradient', skyTop: 'p5', skyHorizon: 'p1', skyBright: 0.5, sun: true, sunSize: 0.36, sunHeight: 6, sunStripes: 9, sunGlow: 0.9, stars: 0.5, far: 90,
          figures: 'gates', figSpace: 22, figDensity: 0.8, figSize: 2.6, figSpin: 15, figThick: 0.05, figBright: 1.6, figGlow: 0.7,
          particles: 'sparks', pCount: 500, pSize: 0.03, pStreak: 1, pSpread: 14,
          speedReact: 10, breathe: 0.12, waves: 1.2, waveSpeed: 50, waveColor: 'p2', fovPunch: 0.06,
        },
      ],
      fx: {
        bloom: { intensity: 0.55, threshold: 0.6 },
        chroma: { react: B('kick', { release: 0.12, threshold: 0.5 }), reactAmount: 0.003 },
        vignette: { amount: 0.4 },
        grain: { amount: 0.04 },
        scanlines: { amount: 0.06, count: 540 },
      },
    },
    {
      id: 'neon-tunnel',
      group: FLIGHTS,
      name: 'Neon Tunnel',
      blurb: 'An endless hexagon tunnel that twists and winds. Every kick sends a ring of light racing ahead, with spinning neon shapes along the way.',
      palette: ['#00f0ff', '#ff00c8', '#7a5cff', '#ffffff', '#05030d'],
      layers: [
        {
          type: 'flight', name: '3D flight', scene: 'tunnel', tunnelShape: 'hexagon', tunnelStyle: 'grid', radius: 3, twist: 2.5, ring: 1.6, lines: 12, winding: 1.4, turns: 1.1, bank: 1.2, sway: 0.25, fov: 80, pitch: 0, speed: 8,
          lineW: 0.05, lineBright: 1.6, lineGlow: 0.4, surface: 0.2, far: 70, fogTo: 'color', fogColor: 'p5',
          figures: 'floating', figSpace: 9, figDensity: 0.75, figSize: 0.7, figSpread: 1.3, figSpin: 60, figThick: 0.03, figBright: 1.8, figGlow: 0.9,
          particles: 'sparks', pCount: 800, pSize: 0.025, pStreak: 1.4,
          speedReact: 12, glowReact: 1.2, breathe: 0.15, figPulse: 0.35, waves: 1.6, waveSpeed: 45, beatFlash: 1.5, fovPunch: 0.1,
        },
      ],
      fx: {
        bloom: { intensity: 0.6, threshold: 0.55 },
        camera: { react: B('kick', { release: 0.15, threshold: 0.5 }), shakeReact: 0.006, zoomReact: 0.015 },
        chroma: { react: B('kick', { release: 0.12, threshold: 0.5 }), reactAmount: 0.004 },
        vignette: { amount: 0.5 },
        grain: { amount: 0.04 },
      },
    },
    {
      id: 'over-the-song',
      group: FLIGHTS,
      name: 'Over the Song',
      blurb: 'Fly over your own track: the mountains are the music about to play, bass on the outside and highs in the middle, under a starry sky.',
      palette: ['#ff3cac', '#2b86c5', '#784ba0', '#ffffff', '#04030a'],
      layers: [
        {
          type: 'flight', name: '3D flight', scene: 'terrain', terrain: 'song', mountains: 6, songWidth: 14, songLayout: 'mirror', songCurve: 1.5, valley: 0.6, road: 2, height: 3.2, pitch: -14, fov: 70, speed: 8, winding: 0.3, turns: 0.6, bank: 0.5, sway: 0.2,
          grid: 1.2, lineW: 0.04, lineBright: 1.5, lineGlow: 0.3, surface: 0.35, surfaceColor: 'p3',
          sky: 'gradient', skyTop: 'p5', skyHorizon: 'p3', skyBright: 0.6, sun: false, stars: 0.8, far: 70,
          figures: 'off', particles: 'dust', pCount: 400, pSize: 0.03, pStreak: 0.3, pSpread: 16,
          glowReact: 0.6, breathe: 0, waves: 0.8, waveSpeed: 30,
        },
      ],
      fx: { bloom: { intensity: 0.5, threshold: 0.6 }, vignette: { amount: 0.45 }, grain: { amount: 0.04 } },
    },
    {
      id: 'neon-lagoon',
      group: FLIGHTS,
      name: 'Neon Lagoon',
      blurb: 'Glide low over a mirror-like lagoon between neon grid islands, past glowing glass structures, with the retro sun reflected in the water.',
      palette: ['#ff4fd8', '#36e2d4', '#ffb347', '#ffffff', '#090418'],
      layers: [
        {
          type: 'flight', name: '3D flight', scene: 'terrain', terrain: 'grid', mountains: 4, size: 1.3, valley: 0.85, road: 4, height: 1.6, pitch: -4, fov: 74, speed: 6, winding: 0.8, turns: 0.7, bank: 0.8, sway: 0.3,
          grid: 2, lineW: 0.05, lineBright: 1.6, lineGlow: 0.35, surface: 0.2,
          sky: 'gradient', skyTop: 'p5', skyHorizon: 'p1', skyBright: 0.55, sun: true, sunSize: 0.34, sunHeight: 5, sunStripes: 8, sunGlow: 0.9, stars: 0.6, far: 85,
          water: true, waterLevel: 1.1, waterColor: '#05031a', clarity: 2, mirror: 0.35, ripple: 0.35, rippleSpeed: 0.8, rippleReact: 0.6,
          structures: true, stStyle: 'glass', stDensity: 0.4, stSpace: 16, stSize: 1.4, stHeight: 8, stTilt: 12, stBright: 1.6, stGlow: 0.7,
          figures: 'off', particles: 'dust', pCount: 400, pSize: 0.03, pStreak: 0.3,
          speedReact: 6, breathe: 0.1, waves: 1, waveSpeed: 40, waveColor: 'p2', fovPunch: 0.05,
        },
      ],
      fx: {
        bloom: { intensity: 0.55, threshold: 0.6 },
        chroma: { react: B('kick', { release: 0.12, threshold: 0.5 }), reactAmount: 0.003 },
        vignette: { amount: 0.45 },
        grain: { amount: 0.04 },
      },
    },
    {
      id: 'alien-planet',
      group: FLIGHTS,
      name: 'Alien Planet',
      blurb: 'Fly low over rocky alien hills and still lakes, past glowing crystals, under a two-tone sky with a pale sun.',
      palette: ['#7cf7ff', '#b45cff', '#ff9e5e', '#ffffff', '#06030f'],
      layers: [
        {
          type: 'flight', name: '3D flight', scene: 'terrain', terrain: 'grid', mountains: 7, size: 1.6, valley: 0.7, road: 3, height: 2.2, pitch: -7, fov: 72, speed: 5, winding: 1, turns: 0.6, bank: 0.8, sway: 0.3,
          surfaceMode: 'material', material: 'rock', matScale: 1, matBright: 1.1, tint: 'p2', tintAmt: 0.3,
          lightColor: '#ffe2c4', lightBright: 1.4, ambient: 0.9,
          sky: 'gradient', skyTop: '#1b3a5c', skyHorizon: 'p3', skyBright: 0.8, sun: true, sunSize: 0.22, sunHeight: 14, sunSide: -18, sunColor1: '#eef9ff', sunColor2: 'p1', sunStripes: 0, sunGlow: 1.2, stars: 0.4, far: 90,
          water: true, waterLevel: 1.4, waterColor: '#06222a', clarity: 4, mirror: 0.15, ripple: 0.25, rippleSize: 1.4, rippleSpeed: 0.6, rippleReact: 0.4,
          structures: true, stShape: 'crystal', stStyle: 'glass', stDensity: 0.5, stSpace: 13, stSize: 1.1, stHeight: 6, stTilt: 25, stEdge: 0.03, stBright: 1.8, stGlow: 0.9,
          figures: 'off', particles: 'dust', pCount: 300, pSize: 0.03, pStreak: 0.2,
          speedReact: 4, glowReact: 0.8, breathe: 0, waves: 0.6, waveSpeed: 30, waveColor: 'p1', fovPunch: 0.04,
        },
      ],
      fx: { bloom: { intensity: 0.45, threshold: 0.7 }, vignette: { amount: 0.4 }, grain: { amount: 0.04 } },
    },
    {
      id: 'chrome-valley',
      group: '3D flights',
      name: 'Chrome Valley',
      blurb: 'Glide down a valley of liquid-chrome mountains over mirror-like water, past glass structures and floating neon shapes, in cool ocean blues.',
      palette: [
        '#00c2a8',
        '#0077b6',
        '#90e0ef',
        '#e0fbfc',
        '#020c17'
      ],
      layers: [
        {
          type: 'flight',
          name: '3D flight',
          enabled: true,
          opacity: 1,
          blend: 'normal',
          upright: false,
          seed: 244041,
          scene: 'terrain',
          terrain: 'valley',
          tunnelShape: 'round',
          tunnelStyle: 'grid',
          res: '1',
          detail: 'high',
          speed: 6,
          height: 2.2,
          pitch: -8,
          fov: 75,
          winding: 1,
          turns: 1,
          bank: 1,
          sway: 0.3,
          mountains: 3.5,
          size: 1,
          rough: 0.5,
          valley: 0.7,
          road: 3,
          cell: 4,
          density: 0.7,
          contour: 0.35,
          songWidth: 12,
          songLayout: 'mirror',
          songCurve: 1.4,
          radius: 3,
          twist: 0,
          ring: 2,
          lines: 12,
          morphSpeed: 0.08,
          grid: 2,
          lineW: 0.06,
          lineGlow: 0.35,
          lineBright: 1.6,
          lineColor: 'p1',
          lineColor2: 'p2',
          surface: 0.25,
          surfaceColor: 'p5',
          windowColor: 'p3',
          surfaceMode: 'material',
          material: 'chrome',
          texSource: 'cover',
          texScale: 12,
          texMirror: true,
          matScale: 5,
          matBright: 3,
          matGlow: 1,
          tint: 'p2',
          tintAmt: 0.36,
          gridOver: false,
          lightColor: '#fff1dc',
          lightBright: 0.57,
          ambient: 0.9,
          shadows: true,
          structures: true,
          stShape: 'mixed',
          stStyle: 'glass',
          stDensity: 0.12,
          stSpace: 4,
          stSize: 8,
          stHeight: 8.2,
          stTilt: 60,
          stEdge: 0.135,
          stBright: 5,
          stGlow: 0.92,
          stPulse: 2,
          stColorMode: 'single',
          stColor: 'p5',
          water: true,
          waterLevel: 0.6,
          waterFill: 0.3,
          waterColor: '#031a24',
          clarity: 3,
          mirror: 0.58,
          ripple: 0.19,
          rippleSize: 0.63,
          rippleSpeed: 2.18,
          rippleReact: 3,
          sky: 'gradient',
          skyTop: 'p5',
          skyHorizon: 'p1',
          skyBright: 1.12,
          sun: false,
          sunSize: 0.35,
          sunHeight: 7,
          sunSide: -27.5,
          sunColor1: 'p3',
          sunColor2: 'p1',
          sunStripes: 8,
          sunGlow: 0.8,
          stars: 1,
          far: 95,
          fogTo: 'transparent',
          fogColor: 'p5',
          figures: 'floating',
          figShape: 'diamond',
          figStyle: 'glass',
          figSpace: 31,
          figDensity: 0.7,
          figSize: 2.3,
          figSpread: 18.7,
          figSpin: -4,
          figThick: 0.04,
          figGlow: 0.8,
          figBright: 1.5,
          figColorMode: 'palette',
          figColor: 'p2',
          particles: 'off',
          pCount: 600,
          pSize: 0.035,
          pSpread: 12,
          pBright: 1,
          pStreak: 0.5,
          pColorMode: 'palette',
          pColor: 'p4',
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 0,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          speedReact: 6,
          glowReact: 1,
          breathe: 0,
          figPulse: 0.3,
          beat: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.15,
            threshold: 0.5,
            punch: 1.5
          },
          waves: 1,
          waveSpeed: 40,
          waveColor: 'p4',
          beatFlash: 1,
          fovPunch: 0
        }
      ],
      fx: {
        bloom: {
          enabled: true,
          threshold: 0.7,
          intensity: 0.45,
          radius: 1,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          reactAmount: 0.3
        },
        camera: {
          spin: 0,
          shake: 0,
          shakeSpeed: 12,
          zoom: 0,
          rotate: 0,
          react: {
            source: 'none',
            lo: 40,
            hi: 120,
            gain: 0,
            attack: 0.005,
            release: 0.18,
            threshold: 0.5,
            punch: 1.5
          },
          shakeReact: 0,
          zoomReact: 0,
          rotateReact: 0
        },
        chroma: {
          amount: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.15,
            threshold: 0.5,
            punch: 1.5
          },
          reactAmount: 0.0485
        },
        glitch: {
          amount: 0.03,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.12,
            threshold: 0,
            punch: 1.5
          },
          reactAmount: 0.16
        },
        flash: {
          color: '#ffffff',
          amount: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.12,
            threshold: 0.5,
            punch: 1.5
          },
          reactAmount: 0
        },
        trails: {
          enabled: false,
          length: 2,
          zoom: 0.15,
          rotate: 0,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.3,
            threshold: 0,
            punch: 1.5
          },
          lengthReact: 3
        },
        color: {
          brightness: 1,
          contrast: 1,
          saturation: 1,
          hue: 0,
          hueSpeed: 0
        },
        vignette: {
          amount: 1,
          softness: 0.71
        },
        grain: {
          amount: 0.04,
          size: 1.5
        },
        scanlines: {
          amount: 0.04,
          count: 100
        }
      }
    },
    {
      id: 'chrome-sunrise',
      group: '3D flights',
      name: 'Chrome Sunrise',
      blurb: 'Skim just above the water through a winding chrome canyon, looking up toward a blazing golden sun, past brightly glowing structures and shapes.',
      palette: [
        '#00c2a8',
        '#0077b6',
        '#90e0ef',
        '#e0fbfc',
        '#020c17'
      ],
      layers: [
        {
          type: 'flight',
          name: '3D flight',
          enabled: true,
          opacity: 1,
          blend: 'normal',
          upright: false,
          seed: 244041,
          scene: 'terrain',
          terrain: 'valley',
          tunnelShape: 'round',
          tunnelStyle: 'grid',
          res: '1',
          detail: 'high',
          speed: 6,
          height: 0.2,
          pitch: 7.5,
          fov: 75,
          winding: 1.99,
          turns: 1.08,
          bank: 1,
          sway: 0.91,
          mountains: 5.1,
          size: 1.49,
          rough: 0.39,
          valley: 0.7,
          road: 7.3,
          cell: 4,
          density: 0.7,
          contour: 0.35,
          songWidth: 12,
          songLayout: 'mirror',
          songCurve: 1.4,
          radius: 3,
          twist: 0,
          ring: 2,
          lines: 12,
          morphSpeed: 0.08,
          grid: 2,
          lineW: 0.06,
          lineGlow: 0.35,
          lineBright: 1.6,
          lineColor: 'p1',
          lineColor2: 'p2',
          surface: 0.25,
          surfaceColor: 'p5',
          windowColor: 'p3',
          surfaceMode: 'material',
          material: 'chrome',
          texSource: 'cover',
          texScale: 12,
          texMirror: true,
          matScale: 5,
          matBright: 3,
          matGlow: 1,
          tint: 'p2',
          tintAmt: 0.36,
          gridOver: false,
          lightColor: '#fff1dc',
          lightBright: 0.57,
          ambient: 0.9,
          shadows: true,
          structures: true,
          stShape: 'mixed',
          stStyle: 'glass',
          stDensity: 0.12,
          stSpace: 4,
          stSize: 8,
          stHeight: 8.2,
          stTilt: 60,
          stEdge: 0.135,
          stBright: 5,
          stGlow: 3,
          stPulse: 2,
          stColorMode: 'single',
          stColor: 'p5',
          water: true,
          waterLevel: 0.6,
          waterFill: 0.3,
          waterColor: '#031a24',
          clarity: 3,
          mirror: 0.58,
          ripple: 0.19,
          rippleSize: 0.63,
          rippleSpeed: 2.18,
          rippleReact: 3,
          sky: 'gradient',
          skyTop: 'p5',
          skyHorizon: 'p1',
          skyBright: 1.12,
          sun: true,
          sunSize: 0.35,
          sunHeight: 7,
          sunSide: -44,
          sunColor1: '#ffffff',
          sunColor2: '#ffd22e',
          sunStripes: 0,
          sunGlow: 3,
          stars: 1,
          far: 95,
          fogTo: 'transparent',
          fogColor: 'p5',
          figures: 'floating',
          figShape: 'diamond',
          figStyle: 'glass',
          figSpace: 23.5,
          figDensity: 0.7,
          figSize: 2.3,
          figSpread: 18.7,
          figSpin: -4,
          figThick: 0.04,
          figGlow: 1.81,
          figBright: 1.5,
          figColorMode: 'palette',
          figColor: 'p2',
          particles: 'off',
          pCount: 600,
          pSize: 0.035,
          pSpread: 12,
          pBright: 1,
          pStreak: 0.5,
          pColorMode: 'palette',
          pColor: 'p4',
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 0,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          speedReact: 6,
          glowReact: 1,
          breathe: 0,
          figPulse: 0.3,
          beat: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.15,
            threshold: 0.5,
            punch: 1.5
          },
          waves: 1,
          waveSpeed: 40,
          waveColor: 'p4',
          beatFlash: 1,
          fovPunch: 0
        }
      ],
      fx: {
        bloom: {
          enabled: true,
          threshold: 0.7,
          intensity: 0.45,
          radius: 1,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          reactAmount: 0.3
        },
        camera: {
          spin: 0,
          shake: 0,
          shakeSpeed: 12,
          zoom: 0,
          rotate: 0,
          react: {
            source: 'none',
            lo: 40,
            hi: 120,
            gain: 0,
            attack: 0.005,
            release: 0.18,
            threshold: 0.5,
            punch: 1.5
          },
          shakeReact: 0,
          zoomReact: 0,
          rotateReact: 0
        },
        chroma: {
          amount: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.15,
            threshold: 0.5,
            punch: 1.5
          },
          reactAmount: 0.0485
        },
        glitch: {
          amount: 0.03,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.12,
            threshold: 0,
            punch: 1.5
          },
          reactAmount: 0.16
        },
        flash: {
          color: '#ffffff',
          amount: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.12,
            threshold: 0.5,
            punch: 1.5
          },
          reactAmount: 0
        },
        trails: {
          enabled: false,
          length: 2,
          zoom: 0.15,
          rotate: 0,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.3,
            threshold: 0,
            punch: 1.5
          },
          lengthReact: 3
        },
        color: {
          brightness: 1,
          contrast: 1,
          saturation: 1,
          hue: 0,
          hueSpeed: 0
        },
        vignette: {
          amount: 1,
          softness: 0.71
        },
        grain: {
          amount: 0.04,
          size: 1.5
        },
        scanlines: {
          amount: 0.04,
          count: 100
        }
      }
    },
    {
      id: 'monstercat',
      group: 'Channel styles',
      name: 'Monstercat-style',
      blurb: 'Row of bars, logo and bold artist/title underneath, floating dust.',
      palette: ['#ffd400', '#ff3c8e', '#3cd2ff', '#ffffff', '#0c0c0e'],
      layers: [
        { type: 'background', mode: 'image', source: 'background', blur: 0.25, brightness: 0.42, saturation: 0.9, zoom: 1.08, drift: 0.25, pulse: 0, color1: '#1a1a1d', color2: '#060607', radius: 1.3 },
        { type: 'particles', mode: 'drift', count: 140, size: 0.0035, sizeVar: 0.7, speed: 0.8, direction: 60, wobble: 0.6, twinkle: 0.3, brightness: 0.55, color: 'p4', react: B('bass', { release: 0.2 }), speedReact: 1.5, sizeReact: 0.2, glowReact: 0.3 },
        {
          type: 'spectrum', name: 'Bars', mode: 'bars', bars: 63, minHz: 30, maxHz: 14000, release: 0.14, smooth: 0.45, gain: 1.05, curve: 1.6, floor: 0.12, tilt: 0.4,
          height: 0.3, minHeight: 0.004, barWidth: 0.68, round: 0, x: 0, y: -0.03, width: 0.8, colorMode: 'single', color: 'p1', glow: 0, pulse: 0,
          v: { y: 0.06, width: 0.9, height: 0.32 },
        },
        { type: 'image', name: 'Logo', source: 'logo', shape: 'square', size: 0.2, x: -0.687, y: -0.29, shadow: 0.25, pulse: 0.015, v: { size: 0.18, x: -0.72, y: -0.075 } },
        {
          type: 'text', line1: '{artist}', line2: '{title}', font: 'Avenir Next', weight1: 800, weight2: 500, size1: 0.072, size2: 0.044, uppercase: true, spacing: 0.02, gap: 0.18,
          align: 'left', x: -0.535, y: -0.29, color1: '#ffffff', color2: '#ffffff',
          v: { x: -0.48, y: -0.075, size1: 0.056, size2: 0.034 },
        },
      ],
      fx: { bloom: { intensity: 0.25, threshold: 0.75 }, vignette: { amount: 0.45 }, grain: { amount: 0.035 } },
    },
    {
      id: 'trapnation',
      group: 'Channel styles',
      name: 'Trap Nation-style',
      blurb: 'Cover art in a circle, layered color ring bouncing with the bass, particles bursting out.',
      palette: ['#7a00ff', '#ff0080', '#00d4ff', '#ffffff', '#120610'],
      layers: [
        { type: 'background', mode: 'image', source: 'background', blur: 0.12, brightness: 0.5, zoom: 1.12, drift: 0.35, color1: '#1a0b2e', color2: '#05020a', react: B('bass', { release: 0.12, punch: 2 }), pulse: 0.05 },
        {
          type: 'particles', mode: 'burst', count: 260, size: 0.0035, sizeVar: 0.6, speed: 1.2, spread: 0.22, twinkle: 0.2, streak: 0.4, brightness: 0.9, color: 'p4',
          react: B('bass', { release: 0.15 }), speedReact: 8, sizeReact: 0.6, glowReact: 0.6, streakReact: 1.5,
        },
        {
          type: 'spectrum', name: 'Ring', mode: 'ring', bars: 120, minHz: 40, maxHz: 10000, release: 0.1, smooth: 0.45, gain: 1.1, curve: 1.5, floor: 0.18, tilt: 1.3,
          height: 0.1, minHeight: 0.004, radius: 0.2, mirror: true, layers: 4, layerSpread: 0.16, layerDelay: 0.035, ringFill: true, colorMode: 'palette', color: 'p4', glow: 0.2,
          react: B('bass', { release: 0.12, punch: 2 }), pulse: 0.08,
        },
        { type: 'image', name: 'Cover art', source: 'cover', shape: 'circle', size: 0.4, border: 0.006, borderColor: 'p4', shadow: 0.3, react: B('bass', { release: 0.12, punch: 2 }), pulse: 0.08 },
        { type: 'text', enabled: false, align: 'center', x: 0, y: -0.78, size1: 0.05, size2: 0.03, v: { y: -0.6 } },
      ],
      fx: {
        bloom: { intensity: 0.45, threshold: 0.7 },
        camera: { react: B('kick', { release: 0.15, threshold: 0.5 }), shakeReact: 0.012, zoomReact: 0.02 },
        chroma: { react: B('kick', { release: 0.15, threshold: 0.5 }), reactAmount: 0.004 },
        vignette: { amount: 0.5 },
        grain: { amount: 0.03 },
      },
    },
    {
      id: 'dubstepgutter',
      group: 'Channel styles',
      name: 'Dubstep Gutter-style',
      blurb: 'Dark and aggressive: white circular bars around the logo, heavy shake, glitch on big hits.',
      palette: ['#ffffff', '#d0d0d0', '#8a8a8a', '#ffffff', '#000000'],
      layers: [
        { type: 'background', mode: 'image', source: 'background', blur: 0.3, brightness: 0.35, saturation: 0.7, zoom: 1.1, drift: 0.4, color1: '#151515', color2: '#000000', react: B('sub', { release: 0.15 }), pulse: 0.03, flash: 0.25 },
        { type: 'particles', mode: 'burst', count: 200, size: 0.003, speed: 1, spread: 0.3, streak: 0.6, brightness: 0.8, color: '#ffffff', react: B('sub', { release: 0.15 }), speedReact: 10, streakReact: 2 },
        {
          type: 'spectrum', name: 'Circle bars', mode: 'circle', bars: 90, mirror: true, direction: 'out', radius: 0.205, height: 0.2, minHeight: 0.006, barWidth: 0.5, round: 0.3,
          minHz: 30, maxHz: 12000, release: 0.1, smooth: 0.25, gain: 1.1, curve: 1.8, floor: 0.12, tilt: 0.5, colorMode: 'single', color: '#ffffff', glow: 0.15,
          react: B('sub', { release: 0.12, punch: 2 }), pulse: 0.06,
        },
        { type: 'image', name: 'Logo', source: 'cover', shape: 'circle', size: 0.4, border: 0.008, borderColor: '#ffffff', fill: true, fillColor: '#000000', shadow: 0.6, shadowColor: '#000000', react: B('sub', { release: 0.12, punch: 2 }), pulse: 0.06 },
        { type: 'text', enabled: false, align: 'center', x: 0, y: -0.78, size1: 0.05, size2: 0.03, v: { y: -0.6 } },
      ],
      fx: {
        bloom: { intensity: 0.35, threshold: 0.7 },
        camera: { react: B('kick', { release: 0.2, threshold: 0.5 }), shakeReact: 0.02, zoomReact: 0.03, rotateReact: 1.2 },
        chroma: { react: B('kick', { release: 0.15, threshold: 0.5 }), reactAmount: 0.008 },
        glitch: { react: B('kick', { release: 0.1, threshold: 0.6 }), reactAmount: 0.35 },
        flash: { react: B('kick', { release: 0.1, threshold: 0.5 }), reactAmount: 0.08 },
        vignette: { amount: 0.65 },
        grain: { amount: 0.06 },
        color: { contrast: 1.1, saturation: 0.9 },
      },
    },
    {
      id: 'ncs',
      group: 'Channel styles',
      name: 'NCS-style',
      blurb: 'Blurred cover background, rounded circular bars, title line below.',
      palette: ['#00b4ff', '#00ffd5', '#ff3cac', '#ffffff', '#020611'],
      layers: [
        { type: 'background', mode: 'image', source: 'background', blur: 0.45, brightness: 0.45, zoom: 1.1, drift: 0.3, color1: '#0b1a2e', color2: '#02050b', pulse: 0.02 },
        { type: 'particles', mode: 'drift', count: 120, size: 0.004, twinkle: 0.6, brightness: 0.6, speed: 0.6, direction: -30, color: '#ffffff' },
        {
          type: 'spectrum', name: 'Circle bars', mode: 'circle', bars: 72, mirror: true, radius: 0.225, height: 0.13, barWidth: 0.55, round: 1, minHeight: 0.008,
          minHz: 35, maxHz: 12000, release: 0.12, smooth: 0.35, curve: 1.5, floor: 0.12, gain: 1.1, colorMode: 'single', color: 'p1', glow: 0.25,
          react: B('bass', { release: 0.15 }), pulse: 0.05,
        },
        { type: 'image', name: 'Cover art', source: 'cover', shape: 'circle', size: 0.42, border: 0.012, borderColor: '#ffffff', react: B('bass', { release: 0.15 }), pulse: 0.05 },
        { type: 'text', line1: '{artist} — {title}', line2: '', weight1: 700, size1: 0.04, uppercase: true, spacing: 0.12, align: 'center', x: 0, y: -0.86, v: { y: -0.62, size1: 0.036 } },
      ],
      fx: { bloom: { intensity: 0.5, threshold: 0.6 }, camera: { react: B('kick', { release: 0.15, threshold: 0.5 }), shakeReact: 0.006 }, vignette: { amount: 0.45 }, grain: { amount: 0.03 } },
    },
    {
      id: 'kaleidoscope',
      group: 'Originals',
      name: 'Kaleidoscope',
      blurb: 'Morphing balls, light blobs, polygons and a vortex, folded through a kaleidoscope.',
      palette: [
        '#8b5cf6',
        '#22d3ee',
        '#f472b6',
        '#ffffff',
        '#07070b'
      ],
      layers: [
        {
          type: 'metaballs',
          name: 'Morphing balls',
          enabled: true,
          opacity: 1,
          blend: 'normal',
          upright: false,
          seed: 926087,
          count: 16,
          size: 0.085,
          sizeVar: 1,
          area: 1,
          x: 0,
          y: 0,
          speed: 1.2,
          style: 'glass',
          edge: 0.036,
          glow: 0,
          wobble: 0,
          colorMode: 'palette',
          color: 'p1',
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.15,
            threshold: 0,
            punch: 1.5
          },
          sizeReact: 0.6,
          speedReact: 1,
          glowReact: 0
        },
        {
          type: 'blobs',
          name: 'Light blobs',
          enabled: true,
          opacity: 1,
          blend: 'screen',
          upright: false,
          seed: 176937,
          mode: 'glow',
          count: 8,
          size: 0.25,
          intensity: 0.14,
          speed: 3.75,
          spread: 1.5,
          x: 0,
          y: 0,
          colorMode: 'palette',
          color: 'p1',
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.35,
            threshold: 0,
            punch: 1.5
          },
          sizeReact: 0.41,
          glowReact: 0.51,
          speedReact: 1.15
        },
        {
          type: 'polygons',
          name: 'Polygons',
          enabled: true,
          opacity: 0.17,
          blend: 'add',
          upright: false,
          seed: 965619,
          mode: 'rings',
          sides: 3,
          count: 16,
          size: 0.205,
          spacing: 0.38,
          stroke: 0.005,
          glow: 0.4,
          fill: 0,
          round: 0.1,
          rotation: 0,
          rotSpeed: 15,
          alternate: true,
          twist: 6,
          ripple: 0.04,
          fadeOuter: 0.4,
          x: 0,
          y: 0,
          orbitRadius: 0.32,
          tunnelSpeed: 0.25,
          colorMode: 'palette',
          color: 'p1',
          color2: 'p2',
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          pulse: 0.16,
          spinReact: 30,
          glowReact: 0.6,
          speedReact: 1
        },
        {
          type: 'vortex',
          name: 'Vortex',
          enabled: true,
          opacity: 0.18,
          blend: 'add',
          upright: false,
          seed: 908311,
          pattern: 'squares',
          density: 20,
          size: 0.95,
          outline: 0.05,
          twist: 0.77,
          speed: 0.35,
          rotSpeed: 4,
          x: 0,
          y: 0,
          hole: 0.05,
          glow: 0.25,
          brightness: 0.75,
          colorMode: 'depth',
          color: 'p1',
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.2,
            threshold: 0,
            punch: 1.5
          },
          speedReact: 0.35,
          pulse: 0,
          flash: 0.5,
          spinReact: 20
        },
        {
          type: 'kaleido',
          name: 'Kaleidoscope',
          enabled: true,
          opacity: 1,
          blend: 'normal',
          upright: false,
          seed: 746880,
          mode: 'radial',
          segments: 4,
          size: 0.22,
          x: 0,
          y: 0,
          rotation: 0,
          spin: 4,
          zoom: 1.11,
          srcX: 0.15,
          srcY: 0.115,
          drift: 0,
          seam: 0,
          seamColor: 'p4',
          seamGlow: 0.3,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          spinReact: 20,
          zoomPulse: 0.08
        }
      ],
      fx: {
        bloom: {
          enabled: true,
          threshold: 0.6,
          intensity: 0.4,
          radius: 1,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.25,
            threshold: 0,
            punch: 1.5
          },
          reactAmount: 0.3
        },
        camera: {
          spin: 0,
          shake: 0,
          shakeSpeed: 12,
          zoom: 0,
          rotate: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.18,
            threshold: 0.5,
            punch: 1.5
          },
          shakeReact: 0,
          zoomReact: 0,
          rotateReact: 0
        },
        chroma: {
          amount: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.15,
            threshold: 0.5,
            punch: 1.5
          },
          reactAmount: 0
        },
        glitch: {
          amount: 0,
          react: {
            source: 'snare',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.12,
            threshold: 0,
            punch: 1.5
          },
          reactAmount: 0
        },
        flash: {
          color: '#ffffff',
          amount: 0,
          react: {
            source: 'kick',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.12,
            threshold: 0.5,
            punch: 1.5
          },
          reactAmount: 0
        },
        trails: {
          enabled: false,
          length: 0.25,
          zoom: 0.15,
          rotate: 0,
          react: {
            source: 'bass',
            lo: 40,
            hi: 120,
            gain: 1,
            attack: 0.005,
            release: 0.3,
            threshold: 0,
            punch: 1.5
          },
          lengthReact: 0
        },
        color: {
          brightness: 1,
          contrast: 1,
          saturation: 1,
          hue: 0,
          hueSpeed: 0
        },
        vignette: {
          amount: 0.35,
          softness: 0.5
        },
        grain: {
          amount: 0.03,
          size: 1.5
        },
        scanlines: {
          amount: 0,
          count: 360
        }
      }
    },
    {
      id: 'liquidneon',
      group: 'Originals',
      name: 'Liquid Neon',
      blurb: 'Glowing morphing balls over drifting colored lights, with light trails.',
      palette: ['#ff2bd6', '#7a5cff', '#22e1ff', '#ffffff', '#07040f'],
      layers: [
        { type: 'background', mode: 'radial', color1: '#140726', color2: '#030108', radius: 1.2, brightness: 1 },
        { type: 'blobs', mode: 'glow', count: 4, size: 0.5, intensity: 0.2, speed: 0.6, spread: 0.8, react: B('bass', { release: 0.4 }), glowReact: 0.6, sizeReact: 0.2 },
        {
          type: 'metaballs', count: 9, size: 0.075, area: 0.62, speed: 1.1, style: 'fill', edge: 0.012, glow: 0.4, wobble: 0.35,
          react: B('bass', { release: 0.15, punch: 1.5 }), sizeReact: 0.7, glowReact: 0.6, speedReact: 1.5,
        },
        { type: 'particles', mode: 'drift', count: 90, size: 0.003, colorMode: 'palette', brightness: 0.6, twinkle: 0.5 },
        { type: 'text', enabled: false, align: 'center', x: 0, y: -0.78, size1: 0.05, size2: 0.03, v: { y: -0.6 } },
      ],
      fx: {
        bloom: { intensity: 0.6, threshold: 0.6, radius: 1.1, reactAmount: 0.3 },
        trails: { enabled: true, length: 0.15, zoom: 0.08 },
        chroma: { amount: 0.0015, react: B('kick', { release: 0.15 }), reactAmount: 0.003 },
        camera: { react: B('kick', { release: 0.15, threshold: 0.5 }), zoomReact: 0.01 },
        vignette: { amount: 0.45 },
        grain: { amount: 0.045 },
      },
    },
    {
      id: 'aurora',
      group: 'Originals',
      name: 'Aurora Chill',
      blurb: 'Soft flowing gradient, thin waveform and elegant title. Lo-fi / ambient.',
      palette: ['#2b1055', '#7597de', '#d16ba5', '#5ee7c4', '#0b0a17'],
      layers: [
        { type: 'blobs', name: 'Flowing gradient', mode: 'mesh', blend: 'normal', count: 5, size: 0.7, intensity: 0.9, speed: 0.35, spread: 0.9, react: B('loud', { release: 0.6 }), glowReact: 0.25, sizeReact: 0.15, speedReact: 0.5 },
        { type: 'blobs', name: 'Soft lights', mode: 'glow', count: 3, size: 0.35, intensity: 0.12, colorMode: 'single', color: '#ffffff', speed: 0.5, react: B('mid', { release: 0.3 }), glowReact: 0.6 },
        { type: 'particles', mode: 'drift', count: 60, size: 0.003, speed: 0.4, twinkle: 0.7, brightness: 0.5, color: '#ffffff' },
        { type: 'spectrum', name: 'Waveform', mode: 'wave', y: -0.42, width: 0.6, height: 0.06, thickness: 0.003, color: '#ffffff', opacity: 0.75, window: 50, stabilize: true, smooth: 0.3, gain: 1, glow: 0.3, mirror: false, v: { y: -0.3, width: 0.8 } },
        {
          type: 'text', line1: '{title}', line2: '{artist}', font: 'Avenir Next', weight1: 300, weight2: 400, size1: 0.075, size2: 0.032, uppercase: false, spacing: 0.18, gap: 0.5,
          align: 'center', x: 0, y: 0, color1: '#ffffff', color2: '#ffffff', glow: 0.4, glowColor: 'p3', v: { size1: 0.06, size2: 0.03 },
        },
      ],
      fx: { bloom: { intensity: 0.25, threshold: 0.85 }, vignette: { amount: 0.35 }, grain: { amount: 0.06, size: 1.8 } },
    },
    {
      id: 'synthwave',
      group: 'Originals',
      name: 'Synthwave',
      blurb: 'Neon grid racing to a striped sun, stars, scanlines.',
      palette: ['#ff2bd6', '#ff7b00', '#ffd319', '#ffffff', '#0d0221'],
      layers: [
        { type: 'background', mode: 'linear', angle: 0, color1: '#05010f', color2: '#240b48', color3: '#7a1c6b', three: true, brightness: 1 },
        { type: 'particles', name: 'Stars', mode: 'drift', count: 220, size: 0.0022, twinkle: 0.8, speed: 0.1, brightness: 0.8, color: '#ffffff' },
        {
          type: 'grid', horizon: -0.12, sun: true, sunY: 0.08, sunSize: 0.25, stripes: 9, sunTop: 'p3', sunBottom: 'p2', gridColor: 'p1', line: 1.6, glow: 0.7, density: 1.4, speed: 0.5,
          camHeight: 0.32, fog: 0.3, react: B('kick', { release: 0.25 }), speedReact: 1.2, gridFlash: 0.6, sunPulse: 0.03,
        },
        {
          type: 'text', line1: '{artist}', line2: '{title}', font: 'Futura', weight1: 700, weight2: 500, size1: 0.065, size2: 0.035, uppercase: true, spacing: 0.15, gap: 0.35,
          align: 'center', x: 0, y: 0.84, color1: '#ffffff', color2: 'p3', glow: 0.8, glowColor: 'p1', v: { y: 0.62, size1: 0.055, size2: 0.03 },
        },
      ],
      fx: {
        bloom: { intensity: 0.7, threshold: 0.55 },
        chroma: { amount: 0.0015 },
        scanlines: { amount: 0.12, count: 540 },
        camera: { react: B('kick', { release: 0.15, threshold: 0.5 }), zoomReact: 0.008 },
        vignette: { amount: 0.5 },
        grain: { amount: 0.05 },
      },
    },
    {
      id: 'techno',
      group: 'Originals',
      name: 'Minimal Techno',
      blurb: 'Black and white square tunnel rushing on the kick, strobe flashes.',
      palette: ['#ffffff', '#bdbdbd', '#7a7a7a', '#ffffff', '#000000'],
      layers: [
        { type: 'background', mode: 'solid', color1: '#000000', brightness: 1 },
        {
          type: 'polygons', mode: 'tunnel', sides: 4, count: 10, size: 0.5, stroke: 0.0025, glow: 0.12, tunnelSpeed: 0.12, speedReact: 0.8, twist: 3, rotSpeed: 4,
          colorMode: 'single', color: '#ffffff', react: B('kick', { release: 0.2 }), pulse: 0.15, glowReact: 0.8, spinReact: 0,
        },
        { type: 'spectrum', name: 'Waveform', mode: 'wave', y: 0, width: 1, height: 0.12, thickness: 0.0025, color: '#ffffff', opacity: 0.6, mirror: false, window: 30, stabilize: true, smooth: 0.15 },
        { type: 'text', enabled: false, align: 'center', x: 0, y: -0.78, size1: 0.05, size2: 0.03, font: 'DIN Condensed', v: { y: -0.6 } },
      ],
      fx: {
        bloom: { intensity: 0.35, threshold: 0.6 },
        flash: { react: B('kick', { release: 0.08, threshold: 0.5 }), reactAmount: 0.12 },
        chroma: { react: B('kick', { release: 0.12, threshold: 0.5 }), reactAmount: 0.006 },
        camera: { react: B('kick', { release: 0.15, threshold: 0.5 }), zoomReact: 0.02 },
        grain: { amount: 0.08 },
        vignette: { amount: 0.55 },
        color: { contrast: 1.15 },
      },
    },
    {
      id: 'blank',
      group: 'Originals',
      name: 'Blank canvas',
      blurb: 'Just a background — build your own look with "Add layer".',
      palette: ['#8b5cf6', '#22d3ee', '#f472b6', '#ffffff', '#07070b'],
      layers: [{ type: 'background', mode: 'radial', color1: '#16141f', color2: '#050508' }],
      fx: { bloom: { intensity: 0.4 } },
    },
  ];

  function apply(project, id) {
    const p = LIST.find((x) => x.id === id);
    if (!p) return false;
    project.look = id;
    project.palette = p.palette.slice();
    project.layers = p.layers.map((spec, i) => {
      const over = Object.assign({}, spec);
      delete over.type;
      const L = VG.project.createLayer(spec.type, over);
      L.id = `${id}-${i}`;
      L.seed = spec.seed != null ? spec.seed : (i + 1) * 1013;
      return L;
    });
    project.fx = VG.project.normalizeFx(p.fx);
    return true;
  }

  VG.presets = { LIST, apply };
})(window.VG);
